// lib/screens/add_patient.dart
import 'package:flutter/material.dart';
import '../models/patient.dart';
import '../services/api_service.dart';

class AddPatient extends StatefulWidget {
  const AddPatient({super.key});

  @override
  // ignore: library_private_types_in_public_api
  _AddPatientState createState() => _AddPatientState();
}

class _AddPatientState extends State<AddPatient> {
  final _formKey = GlobalKey<FormState>();
  String name = '';
  int age = 0;
  String contact = '';
  String address = '';
  String medicalHistory = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Patient'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: ListView(
            children: <Widget>[
              // Name Field
              TextFormField(
                decoration: const InputDecoration(labelText: 'Name'),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter the patient\'s name';
                  }
                  return null;
                },
                onSaved: (value) {
                  name = value!;
                },
              ),
              // Age Field
              TextFormField(
                decoration: const InputDecoration(labelText: 'Age'),
                keyboardType: TextInputType.number,
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Please enter the patient\'s age';
                  }
                  if (int.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
                onSaved: (value) {
                  age = int.parse(value!);
                },
              ),
              // Contact Field
              TextFormField(
                decoration: const InputDecoration(labelText: 'Contact'),
                onSaved: (value) {
                  contact = value!;
                },
              ),
              // Address Field
              TextFormField(
                decoration: const InputDecoration(labelText: 'Address'),
                onSaved: (value) {
                  address = value!;
                },
              ),
              // Medical History Field
              TextFormField(
                decoration: const InputDecoration(labelText: 'Medical History'),
                onSaved: (value) {
                  medicalHistory = value!;
                },
              ),
              const SizedBox(height: 20),
              // Submit Button
              ElevatedButton(
                onPressed: () async {
                  if (_formKey.currentState!.validate()) {
                    _formKey.currentState!.save();
                    Patient newPatient = Patient(
                      id: '', // ID will be generated by backend
                      name: name,
                      age: age,
                      contact: contact,
                      address: address,
                      medicalHistory: medicalHistory,
                    );
                    bool success = await ApiService.addPatient(newPatient);
                    if (success) {
                      // ignore: use_build_context_synchronously
                      Navigator.pop(context, true);
                    } else {
                      // ignore: use_build_context_synchronously
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text('Failed to add patient')),
                      );
                    }
                  }
                },
                child: const Text('Add Patient'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
